export const osName = "modOS Sevda Çiçeği";
export const osVersion = "v1.0.0-beta";
export const structureCache = "/cache/";
export const structurePackages = "/packages/"
export const structureUsr = "/usr/";
export const structureUsrDocuments = "/usr/documents/";
export const structureUsrMedia = "/usr/media/";
export const libJSONloc = "/cache/lib.json";
export const usrSettingsLoc = "/usr/settings.json";
export const sysPackages = ["com.krambo345.terminal", "com.krambo345.desktop"];
export const startUpPackages = ["com.krambo345.desktop", "com.krambo345.wer"]